obstacle_range: 70.0
raytrace_range: 80.0
footprint: [[-0.245, -0.250], [-0.245, 0.250], [0.245, 0.250], [0.245, -0.250]]
inflation_radius: 1.0
cost_scaling_factor: 10.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: pioneer3at/Sick_LMS_291, observation_persistence: 0.0, data_type: LaserScan, topic: /pioneer3at/Sick_LMS_291/laser_scan/layer0, marking: true, clearing: true}
